{{- if .Values.starrocksBeSpec }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template  "starrockscluster.be.configmap.name" . }}
  namespace: {{ template "starrockscluster.namespace" . }}
  labels:
    cluster: {{ template "kube-starrocks.name" . }}
    app: "be"
data:
{{ include "starrocksclster.be.config" . | indent 2 }}
{{- if .Values.starrocksCluster.objectStorage }}
    object_storage_endpoint_use_ssl = {{ toYaml .Values.starrocksCluster.objectStorage.use_ssl }}
    object_storage_endpoint = {{ toYaml .Values.starrocksCluster.objectStorage.endpoint }}
    object_storage_access_key_id = {{ toYaml .Values.starrocksCluster.objectStorage.access_key_id }}
    object_storage_secret_access_key = {{ toYaml .Values.starrocksCluster.objectStorage.secret_access_key }}
    object_storage_max_connection = {{ toYaml .Values.starrocksCluster.objectStorage.max_connection }}
    object_storage_endpoint_path_style_access = {{ toYaml .Values.starrocksCluster.objectStorage.path_style_access }}
{{- end }}
{{- end }}
