apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "starrockscluster.fe.configmap.name" . }}
  namespace: {{ template "starrockscluster.namespace" . }}
  labels:
    cluster: {{ template "kube-starrocks.name" . }}
    app: "fe"
data:
{{ include "starrockscluster.fe.config" . | indent 2 }}
{{- if .Values.starrocksCluster.objectStorage }}
  core-site.xml: |-
    <configuration>
        <property>
          <name>fs.s3a.connection.ssl.enabled</name>
          <value>{{ .Values.starrocksCluster.objectStorage.use_ssl }}</value>
        </property>
        <property>
          <name>fs.s3a.endpoint</name>
          <value>{{ toYaml .Values.starrocksCluster.objectStorage.endpoint }}</value>
        </property>
        <property>
          <name>fs.s3a.access.key</name>
          <value>{{ toYaml .Values.starrocksCluster.objectStorage.access_key_id }}</value>
        </property>
        <property>
          <name>fs.s3a.secret.key</name>
          <value>{{ toYaml .Values.starrocksCluster.objectStorage.secret_access_key }}</value>
        </property>
        <property>
          <name>fs.s3a.connection.maximum</name>
          <value>{{ toYaml .Values.starrocksCluster.objectStorage.max_connection }}</value>
        </property>
        <property>
          <name>fs.s3a.path.style.access</name>
          <value>{{ toYaml .Values.starrocksCluster.objectStorage.path_style_access }}</value>
        </property>
        <property>
          <name>fs.s3a.impl</name>
          <value>org.apache.hadoop.fs.s3a.S3AFileSystem</value>
        </property>
        <property>
          <name>fs.AbstractFileSystem.s3a.impl</name>
          <value>org.apache.hadoop.fs.s3a.S3A</value>
        </property>
    </configuration>
{{- end }}